'use client'

import { FormEvent } from 'react'
import { ArrowLeft, Check, GraduationCap } from 'lucide-react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import Image from 'next/image'
import Logo from '@/public/logo_sidebar.png'

export default function MadarAuth({ signup = false }: { signup?: boolean }) { const router = useRouter(); const submit = (e: FormEvent) => { e.preventDefault(); router.push('/dashboard') }; return <main className="auth-page" dir="rtl"><div className="auth-aside"><Link href="/" className="marketing-logo"><Image src={Logo} alt='logo' width={80} height={80} loading='lazy'/> </Link><div><p className="marketing-eyebrow">Madar</p><h1>{signup ? 'ابدأ تنظيم حصصك.' : 'إدارة حصصك أسهل.'}</h1><p>من أول المجموعة لحد متابعة أداء الطلاب، كل حاجة في مكان واحد.</p><div className="auth-perk"><Check /> حضور بدون ورق</div><div className="auth-perk"><Check /> مصروفات واضحة</div><div className="auth-perk"><Check /> نظام معمول للمدرس</div></div><small>© 2026 Madar</small></div><section className="auth-card"><Link href="/" className="mobile-auth-logo"><span className="logo-mark"><GraduationCap size={18} /></span>Teacher<span>OS</span></Link><p className="marketing-eyebrow">{signup ? 'ابدأ مجانًا' : 'مرحبًا بعودتك'}</p><h2>{signup ? 'ابدأ تنظيم حصصك' : 'مرحبًا بعودتك 👋'}</h2><p className="auth-description">{signup ? 'أنشئ حسابك وابدأ في ترتيب يومك.' : 'سجل دخولك للوصول إلى لوحة التحكم.'}</p><form onSubmit={submit}>{signup && <div className="auth-row"><label>الاسم الأول<input required placeholder="أحمد" /></label><label>اسم العائلة<input required placeholder="محمد" /></label></div>}{signup && <label>رقم الهاتف<input required type="tel" placeholder="01xxxxxxxxx" /></label>}<label>البريد الإلكتروني<input required type="email" placeholder="ahmed@example.com" /></label><label>كلمة المرور<input required type="password" placeholder="••••••••" /></label><button className="marketing-button full" type="submit">{signup ? 'إنشاء حساب' : 'تسجيل الدخول'} <ArrowLeft size={16} /></button></form><p className="auth-switch">{signup ? 'لديك حساب بالفعل؟' : 'ليس لديك حساب؟'} <Link href={signup ? '/login' : '/signup'}>{signup ? 'تسجيل الدخول' : 'ابدأ مجانًا'}</Link></p></section></main> }
